Add ability to configure StatsD hostname/port via environment variables.
manheim/passenger-datadog pull request #4
Opened 2018-01-12 23:26 UTC by dmitrym0

Super simple patch to allow dd-agent/statsd hostname to be set via the environment. Running passenger-datadog in a container environment and dd-agent is running as a separate container.

2018-01-15 23:16 UTC, rrosenblum requested changes
Thanks for the PR. This is a great idea. I would prefer to see it implemented using Ruby's [`OptionParser`](http://ruby-doc.org/stdlib-2.4.2/libdoc/optparse/rdoc/OptionParser.html). 

Since this uses the [`daemons`](https://github.com/thuehlinger/daemons) gem, options will have to be passed in using an extra `--`.

```
 +$ passenger-datadog [start|stop|restart|status] -- --host=dd-agent.local --port=8125
```

2018-01-16 15:02 UTC, rrosenblum commented
If the `STATSD_HOSTNAME` and `STATSD_PORT` environment variables are already used by `statsd`, or common programs that use `statsd`, then I am open to accepting this PR as is. In a quick search, I have not seen those used elsewhere.

2018-01-16 16:58 UTC, dmitrym0 commented
@rrosenblum, OptionParser approach makes sense, for consistency if no other reason.

My naming choice for the environment variables was pretty much random. I'll take a peek to see if this functionality already exists through the statsd gem though, then there would be no changes required for passenger-datadog.

2018-01-16 17:10 UTC, dmitrym0 commented
Looks like statsd configures itself through `STATSD_ADDR` ([here](https://github.com/Shopify/statsd-instrument)). I guess there's no need for this PR.

2018-01-31 23:42 UTC, dmitrym0 commented
Whoops, reopening this. Turns out I linked to `statsd-instrument` above,  but passenger-datadog uses `datadog/statsd` which is similar but different :)

2018-02-18 20:14 UTC, dmitrym0 commented
@rrosenblum, it doesn't look like daemons gem supports extending command line parameters. That means I'll have to add independent `OptionParser` code to passenger-datadog, including help and error handling. Are you ok with that?

2018-02-19 13:42 UTC, rrosenblum commented
@dmitrym0 Yes, that sounds like a good option to me. Let me know if you need any help with the implementation.

2018-02-20 01:29 UTC, dmitrym0 commented
@rrosenblum well, I'm struggling against daemons limitations a bit -- I can't find a way to add another flag to usage to indicate that you can supply statsd hostname/params. If you have a `-h` on the command line, daemons prints usage and exists, see [here](https://github.com/thuehlinger/daemons/blob/master/lib/daemons/cmdline.rb#L32-L35).

2018-02-20 13:56 UTC, rrosenblum commented
hmm, I hadn't really considered the idea of extending daemons options to contain `passenger-datadogs` options. It looks like we will have to have a separate set of help messages that prints out when running `passenger-datadog -- [-h|--help]`. It would be nice to be able to extend the deamons options, but without modifying their code, that doesn't seem like a possibility.

2018-11-13 13:33 UTC, rrosenblum commented
@dmitrym0 this has taken longer than I would have expected it to. Given that, I would be willing to pull in your change to use environment variables rather than options. We can always change this later on, and I would like to ensure `passenger-datadog` can function for everyone's needs. There are currently some merge conflicts in this pull request. If you resolve them, I will merge this in. If you don't have the time to make the changes, I will try to get around to them soon.

2018-11-13 17:32 UTC, dmitrym0 commented
@rrosenblum I'll take a look (this week). I don't recall where I left this off so I need to jump back in.

2022-08-29 21:37 UTC, dmitrym0 commented
Hi folks, I believe this has gone stale, so closing it.

2022-08-29 21:37 UTC, closed without merging